## Numpy Array operations

In [59]:
import numpy as np

In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic Slicing", arr[2:7])
print("with step", arr[1:8:2])
print("Negative indexing", arr[-3])

basic Slicing [3 4 5 6 7]
with step [2 4 6 8]
Negative indexing 8


In [61]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific elements", arr_2D[1,2])   
print("entire row: ",arr_2D[1])
print("entire column: ",arr_2D[:,1])               

Specific elements 6
entire row:  [4 5 6]
entire column:  [2 5 8]


## Sorting


In [62]:
unsorted = np.array([1,1,4,1,5,9,2,6])
print("Sorted Array", np.sort(unsorted))


arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("soerted 2D array by column", np.sort(arr_2D_unsorted, axis = 0))



Sorted Array [1 1 1 2 4 5 6 9]
soerted 2D array by column [[1 1]
 [2 2]
 [3 3]]


np.array() → creates array
np.sort() → sorts data
axis=0 → column-wise
axis=1 → row-wise

## Filter

In [63]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]# you can write expression here 
print("Even numbers", even_numbers)


Even numbers [ 2  4  6  8 10]


##Filter with mask

In [64]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy  indexing vs np.where()



In [65]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Np where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np where [ 6  7  8  9 10]


In [66]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


np.where(condition, value_if_true, value_if_false)

## Adding and Removing Data

In [67]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibility



In [68]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [69]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) # vstack used to add row 
print(original)
print(with_new_row)


new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [70]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5]
