# lets recap 

In [69]:
import numpy as np

creating array from list

In [70]:
arr_id = np.array([1,2,3,4,5])
print("1D array:", arr_id)



arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2D)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### list vs numpy array


In [71]:
Py_list = [1,2,3]
print("python list multiplication", Py_list * 2)



np_array = np.array([1,2,3])
print("Python array multiplication", np_array * 2)

python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]


In [72]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start)


 List operation time:  0.7129833698272705


## creating array from scratch


In [73]:
zeros = np.zeros((3,4))
print("zeroes array: \n", zeros)


ones = np.ones((2,3))
print("0nes array: \n", ones)


full = np.full((2,2),7)
print("full array: \n", full)


random = np.random.random((2,3))
print("random array: \n", random)


sequence = np.arange(0,10,2)
print("sequence array\n", sequence)

zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0nes array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.53350881 0.11819702 0.27582953]
 [0.20232989 0.46288404 0.9319961 ]]
sequence array
 [0 2 4 6 8]


## vector, Matrix and Tensor


In [74]:
vector = np.array([1,2,3])
print("Vector",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ", matrix)


tensor = np.array([[[1,2],[3,3]],
                   [[5,6], [7,8]]])

print("Tensor: ", tensor)

Vector [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 3]]

 [[5 6]
  [7 8]]]


# Array properties




In [75]:
arr = np.array([[1,2,3],
[4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Dtype", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Dtype int64


## Array Reshaping

In [76]:
arr = np.arange(12)
print("Originial array ",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)


raveled = reshaped.ravel()
print("\n relaved array ", raveled) # return view, instead of copy


#Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Originial array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 relaved array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
