In [1]:
import numpy as np

In [2]:
#create-from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr2.dtype)


arr2D = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


numpay are usually homogeneous so when we put one string "prime" in it so it's convert all value in shame data type
i.e string

to print data type we use
---->>    arr_name.dtype
here u21 ---->> u means unicode


shape --->> 
shape means (dimensions) dimen means ttl number of element  in array





In [3]:
#create scratch
arr1 = np.zeros((2,3),dtype="int64") #prefill  
#we an also change type through dtype 
print(arr1,arr1.shape)

arr3 = np.ones((5,6))
print(arr3,arr3.shape)


arr4 = np.full((3,4),100) #prefill with value
print(arr4, arr4.shape)


arr5 = np.eye((3)) #prefill with identity matrix  pass single value.     identity matrix-only diagonal value = 1 
print(arr5, arr5.shape)

arr6 = np.arange(1,10) # range like a python
print(arr6, arr6.shape)


arr7 = np.linspace(1,100,4) #evenly spaced arrays       syntax:-👉linespace(start,end,total number)
print(arr7, arr7.shape)





[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] (5, 6)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)


# 📘 NumPy Basics

🌲 **1. import numpy as np**  
→ Import NumPy library with short name `np`

🌲 **2. np.array()**  
→ Create array from list  
Example: `np.array([1,2,3])`

🌲 **3. type(arr)**  
→ Shows type → `numpy.ndarray`

🌲 **4. arr.shape**  
→ Shows dimensions  
Example: `(3,)`, `(2,2)`

🌲 **5. arr.dtype**  
→ Shows data type (int, float, string)

🌲 **6. 2D Array**  
→ Matrix form  
Example: `[[1,2],[3,4]]`

🌲 **7. np.zeros((m,n))**  
→ Array filled with 0

🌲 **8. np.ones((m,n))**  
→ Array filled with 1

🌲 **9. np.full((m,n), value)**  
→ Array filled with given value

🌲 **10. np.eye(n)**  
→ Identity matrix (diagonal = 1)

🌲 **11. np.arange(start, end)**  
→ Like range (end not included)

🌲 **12. np.linspace(start, end, num)**  
→ Evenly spaced values

In [4]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)   #dimensions = m x n
print(arr.size)    #total elements - 9
print(arr.dtype)
print(arr.ndim)


float_arr = arr.astype(np.float64) #change of type using astype
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


# 📘 NumPy Properties

🌲 **1. arr.shape**  
→ Shows dimensions (rows, columns)  
Example: `(3,3)`

🌲 **2. arr.size**  
→ Total number of elements  
Example: 3×3 = 9

🌲 **3. arr.dtype**  
→ Shows data type of elements  
Example: `int64`, `float64`

🌲 **4. arr.ndim**  
→ Number of dimensions  
1D → 1  
2D → 2  

🌲 **5. astype()**  
→ Used to change data type  
Example: `arr.astype(float)`