In [1]:
import numpy as np

In [2]:
#create-from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr2.dtype)


arr2D = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


numpay are usually homogeneous so when we put one string "prime" in it so it's convert all value in shame data type
i.e string

to print data type we use
---->>    arr_name.dtype
here u21 ---->> u means unicode


shape --->> 
shape means (dimensions) dimen means ttl number of element  in array



