In [27]:
import numpy as np

In [28]:
#create-from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr2.dtype)


arr2D = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


numpay are usually homogeneous so when we put one string "prime" in it so it's convert all value in shame data type
i.e string

to print data type we use
---->>    arr_name.dtype
here u21 ---->> u means unicode


shape --->> 
shape means (dimensions) dimen means ttl number of element  in array





In [ ]:
#create scratch
arr1 = np.zeros((2,3),dtype="int64") #prefill  
#we an also change type through dtype 
print(arr1,arr1.shape)

arr3 = np.ones((5,6))
print(arr3,arr3.shape)


arr4 = np.full((3,4),100) #prefill with value
print(arr4, arr4.shape)


arr5 = np.eye((3)) #prefill with identity matrix  pass single value.     identity matrix-only diagonal value = 1 
print(arr5, arr5.shape)

arr6 = np.arange(1,10) # range like a python
print(arr6, arr6.shape)


arr7 = np.linspace(1,100,4) #evenly spaced arrays       syntax:-👉linespace(start,end,total number)
print(arr7, arr7.shape)





[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] (5, 6)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)
