** operations on numpy Arrays **

In [1]:
import numpy as np

In [2]:
#operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()  # 2D  => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


# 📘 Operations on Arrays

🌲 **1. reshape()**  
→ Changes shape of array (rows, columns)  
→ Total elements must remain same  

Example:  
`(2,3) → (3,2)`

---

🌲 **2. flatten()**  
→ Converts multi-dimensional array into 1D array  

Example:  
`[[1,2,3],[4,5,6]] → [1,2,3,4,5,6]`

In [3]:
#indexing
arr = np.array([1,2,3,4,5])

print(arr[0])  #1
print(arr[3])  #4

1
4


In [4]:
#indexing for 2D array
arr1 = np.array([[1,2,3],[4,5,6]])

print(arr1[0][2]) # here (arr_name[row][column])

3


In [5]:
#fancy indexing
arr = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [6]:
#Boolean Indexing
arr = np.array([1,2,3,4,5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2!= 0])

[3 4 5]
[2 4]
[1 3 5]


In [7]:
#slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4]) #[start,end,step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [8]:
#Copy vs View
#using python
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

# using numpy
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)


sub_arr[0] = 200

print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


# 📘 Indexing in NumPy

🌲 **1. Basic Indexing (1D Array)**  
→ Access elements using index  
Example:  
`arr[0]` → first element  
`arr[3]` → fourth element  

---

🌲 **2. Indexing in 2D Array**  
→ Access using row and column  
Syntax: `arr[row][column]`  
Example:  
`arr[0][2]` → 1st row, 3rd column  

---

🌲 **3. Fancy Indexing**  
→ Access multiple elements using list of indices  
Example:  
`arr[[0,1,3]]` → picks elements at index 0,1,3  

---

🌲 **4. Boolean Indexing**  
→ Filter elements using conditions  

Examples:  
`arr[arr > 2]` → elements greater than 2  
`arr[arr % 2 == 0]` → even numbers  
`arr[arr % 2 != 0]` → odd numbers  

---

🌲 **5. Slicing**  
→ Get subarray using range  
Syntax: `[start : end : step]`  

Examples:  
`arr[1:4]` → index 1 to 3  
`arr[1:]` → from index 1 to end  
`arr[:4]` → from start to index 3  
`arr[::2]` → step = 2  

---

🌲 **6. Copy vs View**

👉 Python List  
→ Creates **copy** (original not affected)

👉 NumPy Array  
→ Creates **view** (original gets affected)

Example:  
Changing sliced array also changes original array in NumPy