** operations on numpy Arrays **

In [1]:
import numpy as np

In [2]:
#operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()  # 2D  => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


# 📘 Operations on Arrays

🌲 **1. reshape()**  
→ Changes shape of array (rows, columns)  
→ Total elements must remain same  

Example:  
`(2,3) → (3,2)`

---

🌲 **2. flatten()**  
→ Converts multi-dimensional array into 1D array  

Example:  
`[[1,2,3],[4,5,6]] → [1,2,3,4,5,6]`