# Numpy
``Axes in multi-dimensional arrays``

# 📐 Array Dimensions and Axes (NumPy)

## 🔹 1D Array
- **1 axis** → `axis 0`

---

## 🔹 2D Array
- **2 axes**
  - `axis 0` → Rows  
    - Operations performed **vertically**
  - `axis 1` → Columns  
    - Operations performed **horizontally**

---

## 🔹 3D Array
- **3 axes**
  - `axis 0` → Depth / Layers  
  - `axis 1` → Rows (in each layer)  
  - `axis 2` → Columns  

---

In [4]:
import numpy as np 

In [5]:
# multi dimensional array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [ ]:
#3D array

arr3D= np.array([[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]]]) # 2 x 3 x 2

print(arr3D,arr3D.shape)

#indexing
print(arr3D[0,1,1])


# slicing
print(arr3D[:,0, :]) # first row from both layers
print(arr3D[:,:, 0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)
4
[[1 2]]
[[ 1  3  5  7  9 11]]


In [ ]:
#vactorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr ** 2)
print(arr * 10)
print(arr + arr2)

In [ ]:
#broadcasting -->> streching the array and used 

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)


#  Vectorization vs Broadcasting

##  Vectorization
- Perform operations on **whole arrays at once**
- No loops needed  
👉 Example: `a + b`

---

##  Broadcasting
- Allows operations on **different size arrays**
- Smaller array is automatically adjusted  
👉 Example: `a + 2`

---

## In Short
- **Vectorization** → Fast array operations (no loops)  
- **Broadcasting** → Makes different shapes work together  