In [1]:
import numpy as np

In [2]:
#Mathematical fux

#aggregation

arr =np.array([1,2,3,4,5])

print(np.sum(arr))      # Sum of all elements
print(np.prod(arr))     # Product (multiplication) of all elements
print(np.min(arr))      # Smallest value in array
print(np.max(arr))      # Largest value in array
print(np.argmin(arr))   # Index of smallest value
print(np.argmax(arr))   # Index of largest value
print(np.mean(arr))     # Average value
print(np.std(arr))      # Standard deviation (spread of data)
print(np.median(arr))   # Middle value after 
print(np.var(arr))      # Variance (measure of data spread, square of standard deviation)


15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


**Variance = average of squared differences from mean**

In [3]:
#power function

arr = np.array([1,2,3,4,5])


print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [4]:
#log

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [5]:
#rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,2,-8,3,4,-5,2,-5])

print(np.unique(arr))
print(np.sqrt(arr))

print(np.abs(arr))

3.0
4.0
3.0
3.0
[-8 -5  1  2  3  4]
[1.         1.41421356        nan 1.73205081 2.                nan
 1.41421356        nan]
[1 2 8 3 4 5 2 5]


/tmp/ipykernel_4145/153950792.py:11: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr))
